### PR TITLE
Bug Fixes/Crash Fixes + Custom Difficulty's + Performance Fixes + More

### PR DESCRIPTION
**Pull request by DaRealDotZ**
----<| FEATURES |>----
Added Custom Difficulty's (You Can Add And Remove Difficulty's).
Added Option To Disable Freeplay Music (Trust Me This Helps Low-End Devices A Lot).
Added Camera Bop Event (Idk Why Val1:CameraMultiplyer Val2:BeatDevider).
Added More Health Bar Colors.
----<| TWEAKS |>----
Made Color Tween Event Longer In Freeplay.
Made Some Code More Simpler.
Health Bar/Icon Now Changes When Character Is Changed (Doesn't Work For Mod Characters For Some Reason Lol).
----<| FIXES|>----
Fixed Title Text  Having A Glitched Animation.
Fixed Rating Being An MFC When Starting A Song.
Fixed Keybinds Being Null When Starting Up The Game For The First Time.
Fixed Intro Text Being Off-Beat.
Fixed Crash When There's No Icon In Chart.
Fixed Crash When There's No GF In Chart.
Fixed Crash When There's No BF In Chart.
Fixed Crash When There's No Dad In Chart.
Fixed Crash When There's No Stage In Chart.
Fixed Crash When There's No Song In Chart (Although Idk If It Works).
Fixed Health Bar Colors Being Inaccurate (I Messed Up With Pico's Icon) .

4 NEW FEATURES, 3 TWEAKS, 11 FIXES

### CODE REVIEW

**Comment by DaRealDotZ** [comment]
P.S Idk What The Spooky Characters Are Doing There I Was Messing With Some Stuff So Nothing Changed

**Comment by SpunBlue** [comment]
Please supply an updated event list text files for events, The original can be found in the Mods Folder.

**Comment by SpunBlue** [comment]
Nevermind

**Comment by SpunBlue** [comment]
Reverted the event code to the old version because you including both the old one and the new one fucks everything up. New events are still included.

**Comment by SpunBlue** [comment]
Also you changed something that shouldn't be changed that causes a lot of issues.

**Comment by SpunBlue** [comment]
Causes too many issues than it fixes.

**Pull request merged**
